services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccj-php-app
    ports:
      - "8081:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: Practicas
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: ccj-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Practicas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
